{% set name = "delayed_image" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/delayed_image-{{ version }}.tar.gz
  sha256: 3df6b59129c13a79b2b67b6fda358c26a48139002b1bfb2b76bcd805b2b6b255

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >3.8
    - setuptools >=41.0.1
  run:
    - python >3.8
    - kwarray >=0.6.19
    - kwimage >=0.10.1
    - networkx >=2.7
    - numpy
    - ubelt >=1.3.6
    - affine >=2.3.0

test:
  imports:
    - delayed_image
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kitware/delayed_image
  summary: The delayed_image module
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Erotemic
    - vicentebolea
