{% set name = "delayed_image" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/delayed_image-{{ version }}.tar.gz
  sha256: 2b47e66bdc38c3c44b262e43353b1757dbef2a6244b6936b688bf9662f7f2e44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=41.0.1
  run:
    - python >={{ python_min }}
    - kwarray >=0.6.19
    - kwimage >=0.10.1
    - networkx >=2.7
    - numpy
    - ubelt >=1.3.6
    - affine >=2.3.0

test:
  imports:
    - delayed_image
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kitware/delayed_image
  summary: The delayed_image module
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Erotemic
    - vicentebolea
